package lab6_alessandroreyes;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
        File archivo = new File("./Inventario.txt");
        Scanner sc = null;
        bebidas = new ArrayList();
        if (archivo.exists()) {
            try {
                sc = new Scanner(archivo);
                sc.useDelimiter(";");
                while (sc.hasNext()) {
                    bebidas.add(new Bebida(sc.next(), sc.next(),sc.next(), sc.nextInt(), sc.nextInt(), sc.nextBoolean(), 
                            sc.nextInt(), sc.next(), sc.nextInt(),sc.nextInt(), sc.next()));
                }
            } catch (Exception e) {
            }
            sc.close();
        }//fin del if
        System.out.println("size: "+bebidas.size());
        for (int i = 0; i < bebidas.size(); i++) {
            System.out.println(bebidas.get(i).getColorantes());
        }
        DefaultTableModel table1 =(DefaultTableModel)jt_cotizacion.getModel();
        for (int i = 0; i < bebidas.size(); i++) {
            Object[] newrow = {
                bebidas.get(i).getCodigo(),
                bebidas.get(i).getMarca(),
                bebidas.get(i).getNombre(),
                bebidas.get(i).getPrecio(),
                bebidas.get(i).getCantidad()
            };
            table1.addRow(newrow);
        }
        jt_cotizacion.setModel(table1);
        
        
        DefaultListModel modelo = (DefaultListModel) jl_eliminar.getModel();
        for (int i = 0; i < bebidas.size(); i++) {
            modelo.addElement("#"+bebidas.get(i).getCodigo()+", "+bebidas.get(i).getNombre());
        }
        jl_eliminar.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarB = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ftf_fecha = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_cantidad = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        tf_codigo = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_cantazucar = new javax.swing.JTextField();
        tf_cantalcohol = new javax.swing.JTextField();
        rb_si = new javax.swing.JRadioButton();
        rb_no = new javax.swing.JRadioButton();
        tf_numlote = new javax.swing.JTextField();
        cb_azul = new javax.swing.JCheckBox();
        cb_rojo = new javax.swing.JCheckBox();
        cb_verde = new javax.swing.JCheckBox();
        cb_amarillo = new javax.swing.JCheckBox();
        cb_blanco = new javax.swing.JCheckBox();
        btn_agregar = new javax.swing.JButton();
        btn_agregar_regresar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jd_cotizacion = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_cotizacion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_cotizacion = new javax.swing.JList<>();
        btn_cotizacion_regresar = new javax.swing.JButton();
        btn_generarcoti = new javax.swing.JButton();
        btn_coti_agregar = new javax.swing.JButton();
        bg_bebidanacional = new javax.swing.ButtonGroup();
        jd_eliminar = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_eliminar = new javax.swing.JList<>();
        btn_eliminar_regresar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jd_modificar = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        Acciones = new javax.swing.JMenu();
        jm_inventario = new javax.swing.JMenu();
        jmi_inventario_agregar = new javax.swing.JMenuItem();
        jmi_inventario_modificar = new javax.swing.JMenuItem();
        jmi_inventario_eliminar = new javax.swing.JMenuItem();
        jmi_cotizar = new javax.swing.JMenuItem();

        jLabel1.setText("Codigo del producto");

        jLabel2.setText("Marca del producto");

        jLabel3.setText("Nombre del producto");

        jLabel4.setText("Cantidad de azucar del producto:");

        jLabel5.setText("Cantidad de alcohol del producto");

        jLabel6.setText("Bebida nacional?");

        jLabel7.setText("Numero de lote del producto");

        jLabel8.setText("Colorantes del producto");

        jLabel9.setText("Precio");

        jLabel10.setText("Cantidad");

        jLabel11.setText("Fecha de vencimiento");

        ftf_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel12.setText("Ejemplo: Nov 22, 2019");

        bg_bebidanacional.add(rb_si);
        rb_si.setSelected(true);
        rb_si.setText("Si");

        bg_bebidanacional.add(rb_no);
        rb_no.setText("no");

        cb_azul.setText("Azul-4");

        cb_rojo.setText("Rojo-69");

        cb_verde.setText("Verde-420");

        cb_amarillo.setText("Amarillo-77");

        cb_blanco.setText("Blanco-07");

        btn_agregar.setText("Agregar a inventario");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_agregar_regresar.setText("Regresar");
        btn_agregar_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar_regresarMouseClicked(evt);
            }
        });

        jLabel13.setText("8_digit");

        javax.swing.GroupLayout jd_agregarBLayout = new javax.swing.GroupLayout(jd_agregarB.getContentPane());
        jd_agregarB.getContentPane().setLayout(jd_agregarBLayout);
        jd_agregarBLayout.setHorizontalGroup(
            jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarBLayout.createSequentialGroup()
                        .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_agregarBLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_marca))
                                .addGroup(jd_agregarBLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_nombre))
                                .addGroup(jd_agregarBLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_cantazucar))
                                .addGroup(jd_agregarBLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_cantalcohol))
                                .addGroup(jd_agregarBLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(33, 33, 33)
                                    .addComponent(rb_si)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rb_no))
                                .addGroup(jd_agregarBLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jd_agregarBLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_numlote, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarBLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(btn_agregar_regresar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_agregarBLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_agregar)
                                        .addComponent(jLabel12))))
                            .addGroup(jd_agregarBLayout.createSequentialGroup()
                                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_cantidad)
                                    .addComponent(tf_precio)))))
                    .addGroup(jd_agregarBLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_azul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_rojo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_verde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_amarillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_blanco)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_agregarBLayout.setVerticalGroup(
            jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarBLayout.createSequentialGroup()
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarBLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)))
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(34, 34, 34)
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(ftf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_cantazucar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_cantalcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rb_si)
                    .addComponent(rb_no))
                .addGap(30, 30, 30)
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_numlote, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_azul)
                    .addComponent(cb_rojo)
                    .addComponent(cb_verde)
                    .addComponent(cb_amarillo)
                    .addComponent(cb_blanco))
                .addGap(34, 34, 34)
                .addGroup(jd_agregarBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_agregar_regresar)))
        );

        jt_cotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Marca", "Nombre", "Precio", "Cantidad en el inventario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_cotizacion);

        jl_cotizacion.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_cotizacion);

        btn_cotizacion_regresar.setText("Regresar");
        btn_cotizacion_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cotizacion_regresarMouseClicked(evt);
            }
        });

        btn_generarcoti.setText("Generar cotizacion");
        btn_generarcoti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_generarcotiMouseClicked(evt);
            }
        });

        btn_coti_agregar.setText("Agregar a la lista");
        btn_coti_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_coti_agregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_cotizacionLayout = new javax.swing.GroupLayout(jd_cotizacion.getContentPane());
        jd_cotizacion.getContentPane().setLayout(jd_cotizacionLayout);
        jd_cotizacionLayout.setHorizontalGroup(
            jd_cotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cotizacionLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jd_cotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_cotizacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_cotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addGroup(jd_cotizacionLayout.createSequentialGroup()
                                .addComponent(btn_cotizacion_regresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_generarcoti))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_cotizacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_coti_agregar)
                        .addGap(104, 104, 104))))
        );
        jd_cotizacionLayout.setVerticalGroup(
            jd_cotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jd_cotizacionLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_coti_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jd_cotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cotizacion_regresar)
                    .addComponent(btn_generarcoti)))
        );

        jl_eliminar.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_eliminar);

        btn_eliminar_regresar.setText("Regresar");
        btn_eliminar_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminar_regresarMouseClicked(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminarLayout = new javax.swing.GroupLayout(jd_eliminar.getContentPane());
        jd_eliminar.getContentPane().setLayout(jd_eliminarLayout);
        jd_eliminarLayout.setHorizontalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btn_eliminar_regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btn_eliminar)
                .addGap(59, 59, 59))
        );
        jd_eliminarLayout.setVerticalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_eliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar_regresar)
                    .addComponent(btn_eliminar))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jd_modificarLayout = new javax.swing.GroupLayout(jd_modificar.getContentPane());
        jd_modificar.getContentPane().setLayout(jd_modificarLayout);
        jd_modificarLayout.setHorizontalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_modificarLayout.setVerticalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Acciones.setText("Acciones");

        jm_inventario.setText("Inventario de bebidas");

        jmi_inventario_agregar.setText("Agregar");
        jmi_inventario_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_inventario_agregarActionPerformed(evt);
            }
        });
        jm_inventario.add(jmi_inventario_agregar);

        jmi_inventario_modificar.setText("Modificar");
        jm_inventario.add(jmi_inventario_modificar);

        jmi_inventario_eliminar.setText("Eliminar");
        jmi_inventario_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_inventario_eliminarActionPerformed(evt);
            }
        });
        jm_inventario.add(jmi_inventario_eliminar);

        Acciones.add(jm_inventario);

        jmi_cotizar.setText("Cotizacion");
        jmi_cotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cotizarActionPerformed(evt);
            }
        });
        Acciones.add(jmi_cotizar);

        jMenuBar1.add(Acciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_inventario_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_inventario_agregarActionPerformed
        this.setVisible(false);
        jd_agregarB.setModal(true);
        jd_agregarB.pack();
        jd_agregarB.setLocationRelativeTo(this);
        jd_agregarB.setVisible(true);
    }//GEN-LAST:event_jmi_inventario_agregarActionPerformed

    private void btn_agregar_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_regresarMouseClicked
        tf_cantalcohol.setText("");
        tf_cantazucar.setText("");
        tf_cantidad.setText("");
        tf_codigo.setText("");
        tf_marca.setText("");
        tf_nombre.setText("");
        tf_numlote.setText("");
        tf_precio.setText("");
        ftf_fecha.setText("");
        rb_si.setSelected(true);
        rb_no.setSelected(false);
        cb_azul.setSelected(false);
        cb_rojo.setSelected(false);
        cb_verde.setSelected(false);
        cb_amarillo.setSelected(false);
        cb_blanco.setSelected(false);
        jd_agregarB.setModal(false);
        jd_agregarB.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_btn_agregar_regresarMouseClicked

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        boolean ver = true;
        for (int i = 0; i < bebidas.size(); i++) {
            if (tf_codigo.getText().equals(bebidas.get(i).getCodigo())) {
                ver = false;
                JOptionPane.showMessageDialog(jd_agregarB, "Un producto existente en el inventario, tiene el mismo codigo y no se puede agregar");
                tf_codigo.setText("");
                break;
            }
        }
        if(Integer.parseInt(tf_cantalcohol.getText()) >= 100){
            ver = false;
                JOptionPane.showMessageDialog(jd_agregarB, "Un producto no puede contener mas de 100% de alcohol");
                tf_cantalcohol.setText("");
        }
        if (ver == true && tf_marca.getText().length() > 0 && tf_cantalcohol.getText().length() > 0 && tf_cantazucar.getText().length() > 0 && 
                tf_cantidad.getText().length() > 0 && tf_codigo.getText().length() > 0 && tf_nombre.getText().length() > 0 &&
                tf_numlote.getText().length() > 0 && tf_precio.getText().length() > 0) 
        {
            try {
                File archivo = new File("./Inventario.txt");
                FileWriter fw = null;
                BufferedWriter bw = null;
                Scanner sc = null;
                try {
                    fw = new FileWriter(archivo, true);
                    bw = new BufferedWriter(fw);
                    bw.write(tf_codigo.getText() + ";");
                    bw.write(tf_marca.getText() + ";");
                    bw.write(tf_nombre.getText() + ";");
                    bw.write(Integer.parseInt(tf_cantazucar.getText()) + ";");
                    bw.write(Integer.parseInt(tf_cantalcohol.getText()) + ";");
                    if (rb_si.isSelected()) {
                        bw.write("true" + ";");
                    } else {
                        bw.write("false" + ";");
                    }
                    bw.write(Integer.parseInt(tf_numlote.getText()) + ";");
                    if (cb_amarillo.isSelected()) {
                        bw.write("Azul-4" + ",");
                    }
                    if (cb_amarillo.isSelected()) {
                        bw.write("Rojo-69" + ",");
                    }
                    if (cb_amarillo.isSelected()) {
                        bw.write("Verde-42" + ",");
                    }
                    if (cb_amarillo.isSelected()) {
                        bw.write("Amarillo-77" + ",");
                    }
                    if (cb_amarillo.isSelected()) {
                        bw.write("Blanco-07" + ",");
                    }
                    bw.write(";");
                    bw.write(Integer.parseInt(tf_precio.getText()) + ";");
                    bw.write(Integer.parseInt(tf_cantidad.getText()) + ";");
                    bw.write(ftf_fecha.getText() + ";");
                    bw.flush();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                bw.close();
                fw.close();
                bebidas = new ArrayList();
                if (archivo.exists()) {
                    try {
                        sc = new Scanner(archivo);
                        sc.useDelimiter(";");
                        while (sc.hasNext()) {
                            bebidas.add(new Bebida(sc.next(), sc.next(), sc.next(), sc.nextInt(), sc.nextInt(), sc.nextBoolean(),
                                    sc.nextInt(), sc.next(), sc.nextInt(), sc.nextInt(), sc.next()));
                        }
                    } catch (Exception e) {
                    }
                    sc.close();
                }
                JOptionPane.showMessageDialog(jd_agregarB, "Bebida creada con exito");
                DefaultListModel modelo = (DefaultListModel) jl_eliminar.getModel();
                for (int i = 0; i < bebidas.size(); i++) {
                    modelo.addElement("#" + bebidas.get(i).getCodigo() + ", " + bebidas.get(i).getNombre());
                }
                jl_eliminar.setModel(modelo);

                DefaultTableModel table1 = (DefaultTableModel) jt_cotizacion.getModel();
                for (int i = 0; i < bebidas.size(); i++) {
                    Object[] newrow = {
                        bebidas.get(i).getCodigo(),
                        bebidas.get(i).getMarca(),
                        bebidas.get(i).getNombre(),
                        bebidas.get(i).getPrecio(),
                        bebidas.get(i).getCantidad()
                    };
                    table1.addRow(newrow);
                }
                jt_cotizacion.setModel(table1);
                tf_cantalcohol.setText("");
                tf_cantazucar.setText("");
                tf_cantidad.setText("");
                tf_codigo.setText("");
                tf_marca.setText("");
                tf_nombre.setText("");
                tf_numlote.setText("");
                tf_precio.setText("");
                ftf_fecha.setText("");
                cb_azul.setSelected(false);
                cb_rojo.setSelected(false);
                cb_verde.setSelected(false);
                cb_amarillo.setSelected(false);
                cb_blanco.setSelected(false);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(jd_agregarB, "Hubo un error al crear la bebida, vuelva a intentarlo");
            tf_cantalcohol.setText("");
            tf_cantazucar.setText("");
            tf_cantidad.setText("");
            tf_codigo.setText("");
            tf_marca.setText("");
            tf_nombre.setText("");
            tf_numlote.setText("");
            tf_precio.setText("");
            ftf_fecha.setText("");
            rb_si.setSelected(true);
            rb_no.setSelected(false);
            cb_azul.setSelected(false);
            cb_rojo.setSelected(false);
            cb_verde.setSelected(false);
            cb_amarillo.setSelected(false);
            cb_blanco.setSelected(false);
        }//fin del if
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_cotizacion_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cotizacion_regresarMouseClicked
        jd_cotizacion.setModal(false);
        jd_cotizacion.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_btn_cotizacion_regresarMouseClicked

    private void jmi_cotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cotizarActionPerformed
        this.setVisible(false);
        jd_cotizacion.setModal(true);
        jd_cotizacion.pack();
        jd_cotizacion.setLocationRelativeTo(this);
        jd_cotizacion.setVisible(true);
    }//GEN-LAST:event_jmi_cotizarActionPerformed

    private void jmi_inventario_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_inventario_eliminarActionPerformed
        this.setVisible(false);
        jd_eliminar.setModal(true);
        jd_eliminar.pack();
        jd_eliminar.setLocationRelativeTo(this);
        jd_eliminar.setVisible(true);
    }//GEN-LAST:event_jmi_inventario_eliminarActionPerformed

    private void btn_eliminar_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminar_regresarMouseClicked
        jd_eliminar.setModal(false);
        jd_eliminar.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_btn_eliminar_regresarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        if (jl_eliminar.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_eliminar.getModel();
            
            bebidas.remove(jl_eliminar.getSelectedIndex());
            try {
                File archivo = new File("./Inventario.txt");
                FileWriter fw = null;
                BufferedWriter bw = null;
                Scanner sc = null;
                try {
                    fw = new FileWriter(archivo, false);
                    bw = new BufferedWriter(fw);
                    for (Bebida t : bebidas) {
                        bw.write(t.getCodigo()+";");
                        bw.write(t.getMarca()+";");
                        bw.write(t.getNombre()+";");
                        bw.write(t.getCantAzucar()+";");
                        bw.write(t.getCantalcohol()+";");
                        bw.write(t.isNacional()+";");
                        bw.write(t.getNumlote()+";");
                        bw.write(t.getColorantes()+";");
                        bw.write(t.getPrecio()+";");
                        bw.write(t.getCantidad()+";");
                        bw.write(t.getFdv()+";");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                bw.close();
                fw.close();
                bebidas = new ArrayList();
                if (archivo.exists()) {
                    try {
                        sc = new Scanner(archivo);
                        sc.useDelimiter(";");
                        while (sc.hasNext()) {
                            bebidas.add(new Bebida(sc.next(), sc.next(), sc.next(), sc.nextInt(), sc.nextInt(), sc.nextBoolean(),
                                    sc.nextInt(), sc.next(), sc.nextInt(), sc.nextInt(), sc.next()));
                        }
                    } catch (Exception e) {
                    }
                    sc.close();
                }
                DefaultTableModel table1 = new DefaultTableModel();
                for (int i = 0; i < bebidas.size(); i++) {
                    Object[] newrow = {
                        bebidas.get(i).getCodigo(),
                        bebidas.get(i).getMarca(),
                        bebidas.get(i).getNombre(),
                        bebidas.get(i).getPrecio(),
                        bebidas.get(i).getCantidad()
                    };
                    table1.addRow(newrow);
                }
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            modelo.remove(jl_eliminar.getSelectedIndex());
            jl_eliminar.setModel(modelo);
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_generarcotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generarcotiMouseClicked
        try {                                             
            File archivo = new File("./Factura.txt");
            FileWriter fw = null;
            BufferedWriter bw = null;
            Scanner sc = null;
            try {
                fw = new FileWriter(archivo);
                bw = new BufferedWriter(fw);
                bw.write("                                          Supermercado EL Barrio");
                bw.newLine();
                bw.write("                                 Factura #1                   "+ new Date());
                bw.newLine();
                bw.write("                               Produc.               cant           Precio");
                bw.newLine();
                for (int i = 0; i < pos.size(); i++) {
                    bw.write("                               "+bebidas.get(pos.get(i)).getNombre()+"                "+bebidas.get(nums.get(i))+"          Lps. "+bebidas.get(pos.get(i)).getPrecio());
                    bw.newLine();
                }
                bw.write("                                                                     TOTAL:");
                bw.newLine();
                int suma=0;
                for (int i = 0; i < pos.size(); i++) {
                    suma= suma + bebidas.get(pos.get(i)).getPrecio();
                }
                bw.write("                                                                        "+suma);
                bw.newLine();
                bw.flush();
            } catch (Exception e) {
                e.printStackTrace();
            }
            bw.close();
            fw.close();
            bebidas = new ArrayList();
            if (archivo.exists()) {
                try {
                    sc = new Scanner(archivo);
                    sc.useDelimiter(";");
                    while (sc.hasNext()) {
                        bebidas.add(new Bebida(sc.next(), sc.next(), sc.next(), sc.nextInt(), sc.nextInt(), sc.nextBoolean(),
                                sc.nextInt(), sc.next(), sc.nextInt(), sc.nextInt(), sc.next()));
                    }
                } catch (Exception e) {
                }
                sc.close();
            }
            JOptionPane.showMessageDialog(jd_cotizacion, "La cotizacion se creo con exito");
            jl_cotizacion.setModel(new DefaultListModel());
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_generarcotiMouseClicked

    private void btn_coti_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_coti_agregarMouseClicked
        if (jt_cotizacion.getSelectedRow() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_cotizacion.getModel();
            int cant = Integer.parseInt(JOptionPane.showInputDialog(jd_cotizacion, "Cuantas quiere agregar?"));
            modelo.addElement("#"+bebidas.get(jt_cotizacion.getSelectedRow()).getCodigo()+", "
                     +bebidas.get(jt_cotizacion.getSelectedRow()).getNombre() + ",   Cantidad: "+ cant);
            jl_cotizacion.setModel(modelo);
            nums.add(cant);
            pos.add(jt_cotizacion.getSelectedRow());
        }
    }//GEN-LAST:event_btn_coti_agregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acciones;
    private javax.swing.ButtonGroup bg_bebidanacional;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregar_regresar;
    private javax.swing.JButton btn_coti_agregar;
    private javax.swing.JButton btn_cotizacion_regresar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_eliminar_regresar;
    private javax.swing.JButton btn_generarcoti;
    private javax.swing.JCheckBox cb_amarillo;
    private javax.swing.JCheckBox cb_azul;
    private javax.swing.JCheckBox cb_blanco;
    private javax.swing.JCheckBox cb_rojo;
    private javax.swing.JCheckBox cb_verde;
    private javax.swing.JFormattedTextField ftf_fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_agregarB;
    private javax.swing.JDialog jd_cotizacion;
    private javax.swing.JDialog jd_eliminar;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JList<String> jl_cotizacion;
    private javax.swing.JList<String> jl_eliminar;
    private javax.swing.JMenu jm_inventario;
    private javax.swing.JMenuItem jmi_cotizar;
    private javax.swing.JMenuItem jmi_inventario_agregar;
    private javax.swing.JMenuItem jmi_inventario_eliminar;
    private javax.swing.JMenuItem jmi_inventario_modificar;
    private javax.swing.JTable jt_cotizacion;
    private javax.swing.JRadioButton rb_no;
    private javax.swing.JRadioButton rb_si;
    private javax.swing.JTextField tf_cantalcohol;
    private javax.swing.JTextField tf_cantazucar;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_numlote;
    private javax.swing.JTextField tf_precio;
    // End of variables declaration//GEN-END:variables
    ArrayList<Bebida> bebidas = new ArrayList();
    ArrayList <Integer> nums = new ArrayList();
    ArrayList <Integer> pos = new ArrayList();
}

